exclude: "data"
repos:
  - repo: https://github.com/psf/black
    rev: "23.12.1"
    hooks:
      - id: black-jupyter

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: ["python/"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: https://github.com/pdm-project/pdm
    rev: 2.12.4 # a PDM release exposing the hook
    hooks:
      - id: pdm-lock-check

  - repo: local
    hooks:
      - id: sync-conda-lock
        name: sync-conda-lock
        language: system
        types: [python]
        pass_filenames: false
        entry: >
          bash -c 'cd python &&
          python -c "
            import utils;
             utils.run_conda_lock(
              replace_file_path=True,
              default_kwargs=True,
            )"'


  # Currently fails to build.
  # See: https://github.com/lorenzwalthert/precommit/issues/476
  # - repo: https://github.com/lorenzwalthert/precommit
  #   rev: v0.3.2
  #   hooks:
  #     - id: readme-rmd-rendered
