project:
  title: "clim-recal"
  type: website
  output-dir: _site
  preview:
    port: 8080
    browser: false
  render:
    - "README.md"
    - "!clim-recal.Rproj"
    - "R/README.md"
    - "R/misc/Identifying_Runs.md"
    - "R/comparing-r-and-python/HADs-reprojection/WIP-Comparing-HADs-grids.md"
    - "docs/reference"
    - "docs/pipeline.qmd"
    - "docs/contributing.md"
    - "docs/pipeline_guidance.qmd"
    - "docs/docker-configurations.qmd"
    - "python/README.md"
      # - "notebooks/Assessing_bc_data/MethodsAssessment_DecWorkshop.Rmd"
      # Requires dataset mounted to run notebook

toc: True
number-sections: True


# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml


website:
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Summary"
        href: "README.md"
      - section: "Pipeline"
        contents:
          - text: "Guidance"
            href: "docs/pipeline_guidance.qmd"
          - text: "Diagram"
            href: "docs/pipeline.qmd"
      - section: "R"
        contents:
          - href: "R/README.md"
            text: Overview
          - href: "R/misc/Identifying_Runs.md"
            text: Identifying Runs
          - section: "Comparing R and Python"
            contents:
              - href: "R/comparing-r-and-python/HADs-reprojection/WIP-Comparing-HADs-grids.md"
                text: "WIP Comparing HADs grids"

      - section: "python"
        contents:
          - "python/README.md"
          - section: "Reference"
            contents:
              - href: "docs/reference/ceda_ftp_download.qmd"
                text: "CEDA Data Access"
              - href: "docs/reference/data_loader.qmd"
                text: "Data Loading"
              - href: "docs/reference/resampling.qmd"
                text: "Data Resampling"
              - section: "Debiasing"
                contents:
                  - href: "docs/reference/debiasing.debias_wrapper.qmd"
                    text: "Wrapper"
              - href: "docs/reference/utils.qmd"
                text: "Utils"
      - text: "Docker"
        href: "docs/docker-configurations.qmd"
      - text: "Contributing"
        href: "docs/contributing.md"


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: python
  dir: docs/reference
  # The below probably requires a non `python` package name
  # dynamic: true
  # render_interlinks: true

  # write sidebar data to this file
  sidebar: _sidebar.yml
  source_dir: ./python/
  # see: https://github.com/alan-turing-institute/clim-recal/issues/128
  sections:
    - title: Data Source Management
      desc: How data is downloaded for use
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - ceda_ftp_download
        # - load_data
        - resampling
        - data_loader
        - debiasing.debias_wrapper
        # - pipeline
        - utils
