version: "3.8"

services:

  jupyter:
    build:
      context: .
      dockerfile: ./compose/jupyter/Dockerfile
      target: clim-recal-base
    ports:
      - "8888:8888"
    # volumes:
    #   - .:/home/jovyan:rw

  docs:
    build:
      context: .
      dockerfile: ./compose/docs/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/home/jovyan

  rstudio:
    build:
      context: .
      dockerfile: ./compose/server/Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio
