name: clim-recal
channels:
  - r
  - defaults
  - conda-forge
dependencies:
  # - r-quarto=1.4
  - python=3.11
  - gdal=3.8.3
  - pip:
    - e ./python  # editable local clim-recal python package
platforms:
  - osx-arm64
  - linux-64
  - linux-aarch64
