name: clim-recal
channels:
  - r
  - defaults
  - conda-forge
dependencies:
  # - r-quarto=1.4
  - python=3.12
  - gdal=3.8.5
  - pdm
  - parallel
  - rsync
platforms:
  - osx-arm64
  - linux-64
  - linux-aarch64
