name: clim-recal
channels:
  - r
  - defaults
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - appnope=0.1.3
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - blosc=1.21.3
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cairo=1.16.0
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.2
  - contourpy=1.0.7
  - cryptography=39.0.0
  - curl=7.86.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.2.0
  - dask-core=2023.2.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - distributed=2023.2.0
  - exceptiongroup=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - fiona=1.8.22
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.1.0
  - gdal=3.6.0
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - iniconfig=2.0.0
  - ipykernel=6.21.2
  - ipython=8.10.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - jupyter_client=8.0.2
  - jupyter_core=5.2.0
  - kealib=1.4.15
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.6.0
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=14.5
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.4
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - msgpack-python=1.0.4
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=3.0
  - nspr=4.35
  - nss=3.78
  - openjpeg=2.5.0
  - openssl=3.0.8
  - parso=0.8.3
  - partd=1.3.0
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - pixman=0.40.0
  - platformdirs=3.0.0
  - pluggy=1.0.0
  - pooch=1.6.0
  - poppler=22.11.0
  - poppler-data=0.4.12
  - postgresql=14.5
  - proj=9.1.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pytest=7.2.1
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pyyaml=6.0
  - pyzmq=25.0.0
  - readline=8.1.2
  - requests=2.28.2
  - rtree=1.0.1
  - scikit-learn=1.1.3
  - scipy=1.10.0
  - setuptools=65.5.0
  - shapely=2.0.1
  - six=1.16.0
  - sortedcontainers=2.4.0
  - sqlite=3.40.1
  - stack_data=0.6.2
  - tblib=1.7.0
  - threadpoolctl=3.1.0
  - tiledb=2.11.3
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzcode=2022g
  - tzdata=2022e
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - wheel=0.37.1
  - xerces-c=3.2.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.13.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - affine==2.3.1
      - attrs==22.1.0
      - certifi==2022.9.24
      - cftime==1.6.2
      - matplotlib==3.6.1
      - netcdf4==1.6.1
      - numpy==1.23.4
      - packaging==21.3
      - pandas==1.5.1
      - pillow==9.4.0
      - pyproj==3.4.0
      - pytz==2022.5
      - rasterio==1.3.3
      - rioxarray==0.12.3
      - snuggs==1.4.7
      - tqdm==4.64.1
      - xarray==2022.10.0