services:

  jupyter:
    user: root
    environment:
      - NB_UID=1001
      - NB_GID=1001
    volumes:
      - /mnt/vmfileshare:/mnt/vmfileshare
      - /datadrive:/datadrive

  rstudio:
    volumes:
      - /mnt/vmfileshare:/mnt/vmfileshare
